# Generated by Django 2.2.14 on 2020-11-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20201105_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Product')),
            ],
        ),
    ]
