# Generated by Django 2.2.14 on 2020-11-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='products',
            new_name='product',
        ),
    ]
